Estimate delivery time
Snowfork/snowbridge pull request #1256
Opened 2024-07-05 00:55 UTC by yrong

More context in https://snowfork.slack.com/archives/G01BGMGLAC9/p1720027597396119

2024-07-24 12:11 UTC, alistair-singh requested changes
Minor comment about removing axios dependency.

2024-07-24 12:11 UTC, alistair-singh commented on web/packages/api/package.json
> +    "axios": "^1.7.2"
Lets remove dependencies on axios and use standard `fetch` api.

2024-07-24 12:11 UTC, alistair-singh commented on web/packages/api/src/utils.ts
> +    let response = await axios.post(graphqlUrl, {
Lets just use fetch here.

2024-07-25 01:42 UTC, yrong commented on web/packages/api/src/utils.ts
> +    let response = await axios.post(graphqlUrl, {
https://github.com/Snowfork/snowbridge/pull/1256/commits/40030b447cf4fe970b2fb43d343936803cbad584

2024-07-26 00:38 UTC, alistair-singh approved these changes

2024-07-26 00:39 UTC, merged