Remove ordered channels
Snowfork/snowbridge pull request #1258
Opened 2024-07-09 18:42 UTC by vgeddes

Makes the gateway support unordered messaging

* Add `Gateway.submitV1` for unordered inbound message delivery
* Modify `Gateway._submitOutbound`  for unordered outbound message acceptance
* Add `Paymaster` contract which now handles message delivery incentivization.

2024-07-10 01:54 UTC, yrong commented on contracts/src/Gateway.sol
> +import {Channel, ChannelID, InboundMessage, OperatingMode, ParaID, Command, MultiAddress, Ticket, Costs} from "./Types.sol";
Seems the format change here is unnecessary?

2024-07-10 02:00 UTC, yrong commented
Seems this PR is mixed with a lot of format change and a bit challenge to review.
@vgeddes, could you check the forge version and make sure the format change here is nessessary?

```
➜ contracts git:(remove-channels) ✗ forge --version
forge 0.2.0 (cafc260 2024-05-02T00:22:11.188280000Z)
```

2024-07-10 02:02 UTC, yrong commented
Seems we need still change on relayer/substrate side to coordinate with the changes here.

2024-07-10 02:09 UTC, yrong commented on contracts/src/Gateway.sol
> +        Verification.Proof calldata headerProof
would it be more clear to rename `leafProof` to `messageProof` and `headerProof` to `mmrProof`?

2024-07-10 22:01 UTC, vgeddes commented
> Seems this PR is mixed with a lot of format change and a bit challenge to review.

Oops, I am using a new editor and I and need to configure it properly. Will revert 👍

2024-07-16 00:50 UTC, yrong requested changes

2025-01-22 14:54 UTC, vgeddes commented
Obsolete

2025-01-22 14:54 UTC, closed without merging